slam_toolbox:
  ros__parameters:
    mode: mapping
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    transform_publish_period: 0.02
    map_update_interval: 5.0
    minimum_time_interval: 0.5
    max_laser_range: 20.0
    correlation_search_space_yaw: 0.314
    loop_search_space_distance: 8.0
    loop_search_minimum_chain_length: 10
    distance_variance_penalty: 0.3
    angle_variance_penalty: 0.2
    coarse_angle_resolution: 0.0349
    fine_angle_resolution: 0.0175
