<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.205"/>
    <xacro:property name="chassis_width" value="0.205"/>
    <xacro:property name="chassis_height" value="0.122"/>
    <xacro:property name="chassis_mass" value="0.8"/>
    <xacro:property name="wheel_radius" value="0.04"/>
    <xacro:property name="wheel_thickness" value="0.017"/>
    <xacro:property name="wheel_mass" value="0.04"/>
    <xacro:property name="wheel_offset_x" value="0.061"/>
    <xacro:property name="wheel_offset_y" value="0.1125"/>
    <xacro:property name="wheel_offset_z" value="0.012"/>
    <xacro:property name="z_offset_global" value="0.01"/>

    <material name="white">
        <color rgba="1.0 1.0 1.0 1"/>
    </material>
    <material name="blue">
        <color rgba="0.0 0.0 1.0 1"/>
    </material>
    <material name="red">
        <color rgba="1.0 0.0 0.0 1"/>
    </material>

    <xacro:macro name="master_wheel" params="name x y joint_name">
        <joint name="${joint_name}" type="continuous">
            <parent link="base_link"/>
            <child link="${name}"/>
            <origin xyz="${x} ${y} ${wheel_offset_z + z_offset_global}" rpy="${pi/2} 0 0"/> 
            <axis xyz="0 0 1"/>
        </joint>
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="${name}">
            <material>Gazebo/Blue</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="mimic_wheel" params="name x y master_joint_name">
        <joint name="${name}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${name}"/>
            <origin xyz="${x} ${y} ${wheel_offset_z + z_offset_global}" rpy="${pi/2} 0 0"/> 
            <axis xyz="0 0 1"/>
            <mimic joint="${master_joint_name}" multiplier="1.0" />
        </joint>
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
            </collision>
        </link>
        <gazebo reference="${name}">
            <material>Gazebo/Blue</material>
        </gazebo>
    </xacro:macro>

    <link name="base_link">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 ${z_offset_global}" rpy="0 0 0"/>
    </joint>
    <link name="base_footprint">
    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${chassis_height/2 - wheel_offset_z + z_offset_global}" rpy="0 0 0"/> 
    </joint>
    <link name="chassis">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <xacro:master_wheel name="wheel_1" x="${wheel_offset_x}" y="-${wheel_offset_y}" joint_name="wheel_1"/>
    <xacro:mimic_wheel name="wheel_3" x="${wheel_offset_x}" y="${wheel_offset_y}" master_joint_name="wheel_2"/>

    <xacro:master_wheel name="wheel_2" x="-${wheel_offset_x}" y="${wheel_offset_y}" joint_name="wheel_3"/>
    <xacro:mimic_wheel name="wheel_4" x="-${wheel_offset_x}" y="-${wheel_offset_y}" master_joint_name="wheel_4"/>

</robot>